[package]
name = "torrent-name-parser"
description = "Torrent name metadata parser"
license = "MIT"
version = "0.9.0"
authors = ["IGI-111 <igi-111@protonmail.com>"]
edition = "2018"
repository = "https://github.com/IGI-111/torrent-name-parser"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.2.1"
lazy_static = "1.3"
smartstring = "0.2.9"
bitflags = "1.3.2"
thiserror = "1.0.30"
result = "1.0.0"

[dev-dependencies]
criterion = "0.3.5"
criterion-macro = "0.3.4"

[[bench]]
name = "benchmark"
harness = false

